ifeq ($(OS),Windows_NT)
    LIBS += -lmingw32 -lSDLmain
    CFLAGS += -DWIN32
else
    UNAME_S := $(shell uname -s)
    ifeq ($(UNAME_S),Darwin)
        FRAMEWORK_FLAGS = -framework Cocoa
	endif
endif

LIBS   += -lSDL_ttf -lSDL_gfx -lSDL_image -lfreetype -ljpeg -lpng -lz -lbz2 -lSDL -lSDLmain -lm -lbz2
CFLAGS += -DSDL1