ifeq (pc,$(MAKECMDGOALS))
	ifeq ($(OS),Windows_NT)
		LIBS += -lmingw32 -lSDL2main
		CFLAGS += -DWIN32
	endif
endif

ADV_LIBS := -lSDL2_gfx -lSDL2_mixer

# check if SIMPLE_SDL2 is defined
ifeq ($(SIMPLE_SDL2),1)
	ADV_LIBS := 
	CFLAGS += -DSIMPLE_SDL2
endif

LIBS    += -lSDL2_ttf -lSDL2_image $(ADV_LIBS) -lmpg123 -lSDL2 -lSDL2main -lfreetype -lpng -lbz2 -ljpeg -lz
CFLAGS  += -DSDL2 -DMUSIC

$(info MAKECMDGOALS: $(MAKECMDGOALS))
$(info CFLAGS: $(CFLAGS))
$(info LIBS: $(LIBS))