include $(HELPERS)/Makefile.sdl2
include $(HELPERS)/Makefile.resin
include $(DEVKITPRO)/wut/share/wut_rules

CFLAGS		+=	-g -Wall -O2 -ffunction-sections \
				-ffast-math \
				$(MACHDEP)

CFLAGS		+=	$(INCLUDE) -D__WIIU__ -D__WUT__ -DUSE_FILE32API -DNOCRYPT -DINPUT_JOYSTICK -DMUSIC -D_XOPEN_SOURCE -DUSE_RAMFS

ASFLAGS		+=	-g $(MACHDEP)
LDFLAGS		+=	-g $(MACHDEP) $(RPXSPECS) -Wl,-Map,$(notdir $*.map)

LIBS		+= -lSDL2_mixer -lmpg123 -lSDL2 -lwut

BUILD		:= build_wiiu
LIBDIRS		:= $(PORTLIBS) $(WUT_ROOT)

SOURCES     += $(CHESTO_DIR)/libs/wiiu_kbd
VPATH       += $(CHESTO_DIR)/libs/wiiu_kbd

export LD	:=	$(CXX)

#-------------------------------------------------------------------------------
ifneq ($(BUILD),$(notdir $(CURDIR)))
#-------------------------------------------------------------------------------

export OUTPUT	:=	$(CURDIR)/$(BINARY)_wiiu

.PHONY: $(BUILD) clean all wiiu

#-------------------------------------------------------------------------------
wiiu: $(BUILD)

$(BUILD): $(SRCFILES)
	@[ -d $@ ] || mkdir -p $@
	@$(MAKE) --no-print-directory -C $(BUILD) -f $(HELPERS)/Makefile.wiiu

#-------------------------------------------------------------------------------
clean:
	@echo clean ...
	@rm -fr $(BUILD) $(BINARY).rpx $(BINARY).elf

#-------------------------------------------------------------------------------
else
.PHONY:	all

DEPENDS	:=	$(OFILES:.o=.d)

#-------------------------------------------------------------------------------
# main targets
#-------------------------------------------------------------------------------
all		:	$(PWD)/$(BINARY).rpx

$(PWD)/$(BINARY).rpx	:	$(OUTPUT).elf

$(OUTPUT).elf	:	$(OFILES)

-include $(DEPENDS)

#-------------------------------------------------------------------------------
endif
#------------------------------------------------------------------------------- 
