name: Build library

on:
  push:
    branches:
      - main
      - sdl2-only
  pull_request:
    branches:
      - main

jobs:
  all:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - platform: pc
            ext: bin
          - platform: wiiu
            ext: wuhb
          - platform: switch
            ext: nro
          - platform: 3ds
            ext: 3dsx
          - platform: wii
            ext: dol
    container:
      image: ghcr.io/fortheusers/sealeo:latest
    steps:
    - uses: actions/checkout@main
      with:
        submodules: recursive
    - name: Build ${{ matrix.platform }} Chestotesto
      run: |
        git clone https://gitlab.com/4TU/chestotesto.git /chestotesto
        cp -rf . /chestotesto/libs/chesto
        (cd /chestotesto && make ${{ matrix.platform }})
        cp /chestotesto/chestotesto.${{ matrix.ext }} chestotesto.${{ matrix.ext }}
    - uses: actions/upload-artifact@v4
      with:
        name: chestotesto.${{ matrix.ext }}
        path: /__w/chesto/chesto/chestotesto.${{ matrix.ext }}
    - if: matrix.platform == 'wiiu'
      uses: actions/upload-artifact@v4
      with:
        name: chestotesto.rpx
        path: /__w/chesto/chesto/chestotesto.rpx